fixed an error that pops up in console log
error: react-dom_client.js?v=ea805598:2312 Invalid DOM property `class`. Did you mean `className`?

cause: class was used instead of classname which jsx didnt like